### ISSUE TITLE
Request - Add prefix number of netmask ip into data sources.

### ISSUE THREAD

**Issue by Kronk74** [vmware/terraform-provider-vcd#595]
Hello,

### Terraform Version
v0.13.4

### Affected Datasource(s)
- vcd_network_direct

It can be interesting to get Gateway CIDR information like we can see into vCloud :

![image](https://user-images.githubusercontent.com/56944280/99537632-34b01200-29ac-11eb-937b-833e5b7d4dbf.png)

With it, we could use cidrhost command for terraform core :)

**Comment by Didainius** [comment]
Hello @Kronk74 ,
We usually resist creating some computation where API doesn't return it. IMHO it would be better to have a function for converting netmask to prefix as it is "UI sugar" in this case and API doesn't return it. I will do an investigation if some function could land into terraform core, but can't promise it now as it is beyond our ownership.

In the meantime one way around it could be to use something like `null` provider (https://registry.terraform.io/providers/hashicorp/null/latest/docs/data-sources/data_source) in combination with some `local_exec` provisioner (https://www.terraform.io/docs/provisioners/local-exec.html) to "outsource" this task to your shell.

**Comment by carmineesposito73** [comment]
Hi @Didainius,
I've opened an issue on terraform core:

https://github.com/hashicorp/terraform/issues/23905#issuecomment-777155511

"it seems like this situation is one which could be resolved by designing any Terraform provider that deals with IP address ranges can accept them in Terraform's standard notation -- the CIDR syntax -- and translate back and forth to other notations as needed when working with systems that have disagreeing conventions"

So the translation should be resolved on provider side.
It's not just a cosmetic issue, for example I cannot source a routed network subnet and then use it in a fw rule, since the two notations are different.
I know the APIs are wrong since they should use the same notation, but at least on terraform side they should use the same.
