### ISSUE TITLE
static routing for nsxv edge

### ISSUE THREAD

**Issue by carmine73** [vmware/terraform-provider-vcd#604]
I'm just asking if static routing on nsxv is in roadmap.
thanks

**Comment by lvirbalas** [comment]
Hi Carmine,

Current plan is a development of NSX-T support (not NSX-V).

**Comment by pasikarkkainen** [comment]
NSX-V is still widely used with VCD so it'd be nice to have these "basic features" also implemented for NSX-V..

**Comment by Didainius** [comment]
Closing this due to stopped NSX-V development. We have this resource for NSX-T https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vapp_static_routing

**Comment by pasikarkkainen** [comment]
@Didainius I understand NSX-v is not supported anymore, but the resource you linked "vapp_static_routing" is not what this issue was for.

This issue is for adding support for static routes on the *edge gateway*, and I don't think there's currently a resource for that, with or without NSX-T.

I should probably open another issue about that as RFE.

**Comment by Didainius** [comment]
> @Didainius I understand NSX-v is not supported anymore, but the resource you linked "vapp_static_routing" is not what this issue was for.
> 
> This issue is for adding support for static routes on the _edge gateway_, and I don't think there's currently a resource for that, with or without NSX-T.
> 
> I should probably open another issue about that as RFE.

Sorry, I was cleaning up things and referenced the wrong thing (vApp static routing resource) You are totally right! We have NSX-T routing on the roadmap

**Comment by pasikarkkainen** [comment]
rfe issue for nsx-t edge static routes: https://github.com/vmware/terraform-provider-vcd/issues/943
