### ISSUE TITLE
Creating Org/oVDC/NSX-T Edge Gateway/Routed Network in one go fails

### ISSUE THREAD

**Issue by medea61** [vmware/terraform-provider-vcd#609]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/vmware/vcd v3.1.0

### Affected Resource(s)
- vcd_org
- vcd_org_vdc
- vcd_nsxt_edgegateway
- vcd_network_routed

### Terraform Configuration Files
I would like to share this privately. Please advise.

### Debug Output
I would like to share this privately. Please advise.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Objects should be created in correct order.

### Actual Behavior
It seems as if the creation of the vcd_nsxt_edgegateway is started before the vcd_org_vdc is ready.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Running `terraform apply` a second time finalized the creation properly.
Doing the reverse (with `terraform destroy`) runs into bascially the same dependency error (in reverse) and also finalized properly of run twice.

**Comment by Didainius** [comment]
Hello @medea61 ,
The existing org vdc networks ar not compatible with nsx-t. We are working heads down to introduce new nsx-t capable org vdc networks.

**Comment by medea61** [comment]
Hi @Didainius
This issue does not involve existing/old objects. 
I am trying to create a whole new configuration top to bottom with nsx-t and I am using the newly released 3.1-type objects which seem to be the missing puzzle pieces. 

From what I can see this issue concerns a dependency/order of execution problem with the new 3.1-type objects (e.g. vcd_nsxt_edgegateway).

**Comment by Didainius** [comment]
Ok, I might misunderstood your statement, but please be aware that existing `vcd_network_X` will not be compatible with NSX-T resources. The reason behind is that Org Vdc networks for NSX-T environment must use new type of API (OpenAPI) endpoints.

> It seems as if the creation of the `vcd_nsxt_edgegateway` is started before the vcd_org_vdc is ready.
Going back to this problem. There may potentially be a problem because `vcd_org_vdc` is put as a name reference. Terraform interpolation might not be making the graph properly (because it is not the `.id` field). Would you be able to put an explicit `depends_on = [vcd_org_vdc.XXXX]` into your `vcd_nsxt_edgegateway` definition to see if it resolves the problem or not.

**Comment by medea61** [comment]
Yes, explicitly referencing the dependency resolves the problem.
What would be the way forward? Code fix or simply documenting the issue?

**Comment by Didainius** [comment]
@medea61 ,
This is something that is how Terraform core works and not in our control. Basically the point is that references should be made by `.id` or at least computed variables, but for historical reasons this provider uses `name` references in quite a few places for historical reasons. We are trying to move to `.id` model for our new resources as we go, but it is not an easy fix. We do attempt to document it as well in some cases, but "multi-resource" examples are not too often due to the nature of documentation format (1 page per resource or data source).

This is a good reminder that we should attempt to both keep the path to use `.id` for references and try to document cases.

Not that it is a very good way, but here is a hack if you want to avoid using explicit `depends_on` statement.
The point of it is that it "pulls in" `.id` field for evaluation of whole value. That way Terraform core is forces to wait until `id` is available.


```hcl
vm_name         = (vcd_vapp_vm.web1.id != "always-not-equal" ? vcd_vapp_vm.web1.name : null)  
```
