### ISSUE TITLE
Feature request: Add new attribute for assigning placement policy to vcd_vapp_vm

### ISSUE THREAD

**Issue by NilsBusche** [vmware/terraform-provider-vcd#614]
### Affected Resource(s)
- vcd_vapp_vm

### Feature request
Starting with vCloud Director 10 it is possible to assigne placement policies to VM resources.

Screenshot from VM configuration in vCloud Director:
![image](https://user-images.githubusercontent.com/41150872/104308744-6daec380-54d1-11eb-99d5-bd1e8146a09a.png)

For screenshot source and additional documentation see: https://vmtechie.blog/2019/09/24/vcloud-director-10-vm-placement-policies/

This feature also should be made available in this Terraform provider.

### Possible Terraform configuration
```hcl
resource "vcd_vapp_vm" "testvm" {
  vapp_name           = vcd_vapp.vapp.name
  name                = "testvm"
  computer_name       = "testvm"
  catalog_name        = "catalog1"
  template_name       = "template1"
  placement_policy_id = "placement-policy-1"
}
```

### Additional ideas
* Configuration might be similar to `sizing_policy_id`
* Maybe a new datasource for the placement policies would be helpful

**Comment by vdudejon** [comment]
This is a little old but I've been working on this as well.  

It looks like placement policies show up when you import a sizing policy.  I tried using a placement policy id instead of a sizing policy, and the VM was built and respected the placement **and** sizing rules of the placement policy.  So it seems like you can just use a placement policy id with the argument `sizing_policy_id`

**Comment by NilsBusche** [comment]
Hi @vdudejon ,

sorry for the late response. In the last months there was no demand for using this feature anymore so we did not take a look at it until these days.

You're right with your idea that we can use `sizing_policy_id` attribute for applying placement policies also.

But there is no read capability for placement policies in the Terraform provider. So if you set a placement policy via Terraform using `sizing_policy_id` attribute and then change the placement policy via the vCloud Director UI, Terraform does not recognize this change and a `terraform plan` displays "No changes".
Same occurs if you import an existing VM with applied placement policy into Terraform. This will not fill `sizing_policy_id` attribute in the statefile.

So I assume we would need an extra attribute for setting placement policies or extend the provider with read capabilities for placement policies.

**Comment by adambarreiro** [comment]
Hello,

Since [v3.8.0](https://registry.terraform.io/providers/vmware/vcd/latest/docs), released a few days ago, both **vcd_vapp_vm** and **vcd_vm** support assigning and reading VM Placement Policies (also they can be assigned to VDCs for that purpose, and created with the new [**vcd_vm_placement_policy**](https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vm_placement_policy) resource)

Please have a look at the changelog [here](https://github.com/vmware/terraform-provider-vcd/blob/main/CHANGELOG.md#380-november-25-2022) for the list with all the new features and improvements on this regard.

Thanks for the feature request and best regards.
