### ISSUE TITLE
error: cannot support 1 CPUs using 2 cores per socket

### ISSUE THREAD

**Issue by lukassup** [vmware/terraform-provider-vcd#634]
### Terraform Version
```
$ terraform -v
Terraform v0.14.5
+ provider registry.terraform.io/vmware/vcd v3.1.0
```

### Affected Resource(s)
- `vcd_vapp_vm`

### Terraform Configuration Files

```hcl
resource "vcd_vapp_vm" "lb1" {
  vdc                    = "my-vdc"
  vapp_name              = "my-vapp"
  name                   = "lb1"
  computer_name          = "lb1"
  catalog_name           = "my-catalog"
  template_name          = "my-template"
  memory                 = "4096"
  cpus                   = 1
  cpu_cores              = 1
  memory_hot_add_enabled = true
  cpu_hot_add_enabled    = true
  # networks & storage drives omitted for brevity
}
```

I'm able to reproduce issue consistently since provider version 3.0 and can provide debug logs if needed.

### Expected Behavior

`terraform apply` to succeed

### Actual Behavior

```
Error: task did not complete successfully:  [409:INVALID_STATE] - [ 1b8370f1-7d23-4c6e-9743-8594acf6cd70 ] Virtual machine "APPPRDLB2-rQUS" cannot support 1 CPUs using 2 cores per socket. CPU count must be a multiple of cores per socket.
```

### Steps to Reproduce
1. `terraform apply`

**Comment by lukassup** [comment]
Looks related to #553

**Comment by Didainius** [comment]
Hello @lukassup ,
Would you be able to share log file as well https://registry.terraform.io/providers/vmware/vcd/latest/docs#logging
That would save us some time.

Thanks!

**Comment by Didainius** [comment]
@lukassup ,
A few more things as I tried to replicate it (and could not) - which version of VCD is it and is it related to specific template?

**Comment by Didainius** [comment]
Identified the issue.

To reproduce the template must have higher `cpu/core` settings than 1. (e.g. 4 and 4).
Then in `vcd_vapp_vm` definition if one sets 1 and 1 while using such template a similar error occurs:
```
error: task did not complete successfully:  [409:INVALID_STATE] - [ f7173785-299f-4734-b9f3-c5dec8fa0be2 ] Virtual machine "web1-57li" cannot support 1 CPUs using 4 cores per socket. CPU count must be a multiple of cores per socket.
```

These are code lines responsible for problem - https://github.com/vmware/terraform-provider-vcd/blob/fc752f0df0c3505d40b961498e2c2ca1d705de35/vcd/resource_vcd_vapp_vm.go#L1014-L1032

What happens is that initially the code tries to only change CPU count (wihout cores) using function `changeCpuCount`, and this is when the error gets reported - because it tries to set 1CPU, but leave 4 cores per socket.

**Comment by lukassup** [comment]
Great find! Do you still need logs for TF run?

**Comment by Didainius** [comment]
> Great find! Do you still need logs for TF run?

Nope. No need.

So before we fix it a workaround could be to have a template which has less CPU/cores specified for the VM.

**Comment by lukassup** [comment]
TYVM :bow:
