### ISSUE TITLE
[Feature request] Assumption of API version leads to WAF problems

### ISSUE THREAD

**Issue by narcoticfresh** [vmware/terraform-provider-vcd#669]
Hi guys..

### Problem

In large organizations, often vCloud and all get updated (and thus their API level goes up), but any components in front of them (like in our case F5) will not be re-trained in order to allow any new operations through. It is sad and annoying, but it tends to happen.

In our case, our API is level 33 - but F5 was hardened on level <30. 

This means, F5 will deny any requests which an "Authorization" header, instead expecting the "x-vcloud-authorization" header for auth.

### Hopeful request

It would be sensational if there would be a setting to set the API level on the provider. I guess when the provider detects a certain level, it would send the "x-vcloud-authorization" header?

Or maybe any other way in order to switch to the "old style" x-vcloud-authorization header..

### Thanks

Thanks for all the work you do here, it is appreciated!

**Comment by Didainius** [comment]
@narcoticfresh ,
Hi and thanks for it. Well we try to stay as "stable" as possible, but we have to bump API to start using new features (and overcome bugs). Also we usually bump API (like now we are bumping V32.0 to V33.0) when the older versions requiring it is End Of Life. The auth mechanism is also deprecated and even now some users have it disabled.

In theory we could add an env var to override API version, but in practice this will cause unexpected errors and crashes (because API bumps usually are not that innocent, especially when our covered surface grows) and we cannot certify that many combinations (all supported API versions on each supported VCD version).

I know what it means to maintain things in an enterprise, but I think if you upgrade VCD you are doomed to switch to new auth (future versions will totally drop it).

Open to more thoughts. As I said API version modification could be done, but there will possibly be random errors very quickly and we cannot support it because of jump.

**Comment by narcoticfresh** [comment]
@Didainius 
yes, your points are spot on.. i wasn't aware that you track EOLs that closely.. so i see, anything that deals with api levels is not a viable option.

> I know what it means to maintain things in an enterprise, but I think if you upgrade VCD you are doomed to switch to new auth (future versions will totally drop it).

also true. reality is, in our organization, i'm not even able to identify which orgs/people are in charge (and willing) to update the F5 rules.. but I'm onto that.

so let's forget the api level approach..

what about this proposition (which should not break BC nor the future):
* there is a new option "support_legacy_auth_mirror" (bad naming)
* when this is enabled, the provider checks *if* the response to `/api/sessions` contains an `x-vcloud-authorization` header
* if setting is enabled and `/api/sessions` had a `x-vcloud-authorization` header, the provider will use this header value for subsequent calls. if not, it will use the official standard way.

using this approach, setups like our broken one would be still fully usable *and* once upstream completely removes `x-vcloud-authorization`, no modifications or ill behavior would be caused by this functionality. thus it can be remove then of course, but there would be no urgency.

**Comment by narcoticfresh** [comment]
@Didainius 
Positively surprised that this issue wasn't closed yet due to inactivity..

Anyway, in our organization we have more recent releases available now - they even fixed the F5 proxy to support the "new" Authorization based request..

Now it fails while retrieving the ORG (` govcd.(*VCDClient).GetAdminOrgByNameOrId-->govcd.getEntityByNameOrId-->govcd.(*VCDClient).GetAdminOrgByNameOrId`) - F5 keeps returning HTML here.. 

I don't see the behavior documented nor is it visible in the logs - does the provider HTTP client relay the cookies set by `Set-Cookie` responses in the subsequent requests? If not, I guess that is our problem here..

**Comment by Didainius** [comment]
@narcoticfresh ,
I am closing this at the moment, but feel free to reopen if you have more comments
