### ISSUE TITLE
Value out of range error when refreshing vcd_vapp_org_network and vcd_vapp_access_control resources

### ISSUE THREAD

**Issue by GeorgiosGoniotakis** [vmware/terraform-provider-vcd#766]
Hello there 😄 Happy New Year to everyone!

### Terraform Version
Terraform Version: 1.1.2 (Windows)
VMWare VCD Provider Version: 3.4.0

### Affected Resource(s)
- vcd_vapp_org_network 
- vcd_vapp_access_control 

### Panic Output
vcd_vapp_org_network : `Error: error finding Vapp: error decoding response: strconv.ParseInt: parsing "215758374800": value out of range`

vcd_vapp_access_control: `Error: [resourceAccessControlVappRead] error retrieving vApp urn:vcloud:vapp:bde66c0f-311c-41f3-8dc2-463a7f5cc93d. error decoding response: strconv.ParseInt: parsing "5456234283520": value out of range`

### Expected Behavior
Refreshing the plan should have happened with no errors.

### Actual Behavior
The errors reported on the `Panic Output` section.

### Steps to Reproduce
Execute `terraform plan`

### References
I have a reason to believe that it could be something similar to this https://github.com/vmware/terraform-provider-vcd/issues/626

**Comment by dataclouder** [comment]
Hi Georgios,
Thanks for reporting this issue, and happy new year!
To understand where the problem is, we need a portion of the logs where it reports the retrieval of the vApp. 
If you don't have the logs, could you repeat the operation with [the field `logging` enabled in the provider section](https://registry.terraform.io/providers/vmware/vcd/latest/docs)?
From the file `go-vcloud-director.log`, look until you find the numbers reported above, and please provide the whole XML structure. The suspected place where this error should be happening is in function `GetVAppByHref` (this will also help you find the place in the logs)

**Comment by GeorgiosGoniotakis** [comment]
Hello @dataclouder Thank you for responding. I enabled logging and produced a file with logs. However, the file is 177 thousand lines long. When filtering for `GetVAppByHref ` and the numbers that I shared with you I am getting several places in the files and different XML structures which are hundreds of lines long. Also the logs contain a ton of sensitive data such as MAC addresses, etc. Is there a way (for example search for some error) to narrow down the list of results please?

**Comment by GeorgiosGoniotakis** [comment]
Hello @dataclouder Thank you for your assistance. It turns out that the error was happening due to a misconfiguration of the build agent from our side. No further assistance will be required and thus I will close this issue. Have a nice afternoon 😄
