### ISSUE TITLE
Plugin did not respond : terraform-provider-vcd may crash with Terraform 1.1+ on some OSes

### ISSUE THREAD

**Issue by Didainius** [vmware/terraform-provider-vcd#769]
Parent issue - https://github.com/hashicorp/terraform/issues/30323

### Problem

We have observed that `terraform-provider-vcd` can crash with Terraform versions between 1.1.0 - 1.1.3 on some Operating Systems and some resources (one known resource is `vcd_catalog_item`)

### Workaround
For now the workaround it is to use Terraform 1.0.X.

#### Sample crash error. 

```
╷
│ Error: Plugin did not respond
│ 
│   with vcd_catalog_item.TestCatalogItemDS,
│   on main.tf line 43, in resource "vcd_catalog_item" "TestCatalogItemDS":
│   43: resource "vcd_catalog_item" "TestCatalogItemDS" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-vcd_v3.5.0 plugin:

fatal error: runtime: netpoll failed

runtime stack:
runtime.throw({0xdd2116, 0xc000113840})
	runtime/panic.go:1198 +0x71
runtime.netpoll(0xc000058000)
	runtime/netpoll_epoll.go:131 +0x316
runtime.findrunnable()
	runtime/proc.go:2756 +0x185
runtime.schedule()
	runtime/proc.go:3367 +0x239
runtime.park_m(0xc000000b60)
	runtime/proc.go:3516 +0x14d
runtime.mcall()
	runtime/asm_amd64.s:307 +0x43
```

**Comment by dataclouder** [comment]
Fixed in [release 3.5.1](https://github.com/vmware/terraform-provider-vcd/releases/tag/v3.5.1)

The VCD plugin was occasionally writing to Terraform `stdout` in order to transmit information to the user. Such use of `stdout` was undocumented, and the availability of the file descriptor that allowed such writing was finally removed in recent versions of Terraform CLI tool.

This fix removes every instance of using the above undocumented behavior, replacing it with the following:

* messages that were used as auxiliary list of items during `terraform import` are now formatted into an error message and displayed through a regular Terraform error, as they should have been in the first place.
*  messages directed to the screen to communicate upload progress or suggest behavior are now written to the plugin log (`go-vcloud-director.log`) with a label (`[SCREEN]`) that makes it easy to find and eventually pipe to a visualization device. such as executing the command below in a separate terminal screen while `terraform apply` is running

```
  tail -f go-vcloud-director.log | grep '\[SCREEN\]'
```
