### ISSUE TITLE
Added a hook to fill OVA parameters

### ISSUE THREAD

**Issue by emmanuelpare** [vmware/terraform-provider-vcd#788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Using the Terraform vcd module I am trying to create a vapp by uploading/using OVA file (ex: VMware Log Insight).  Is it possible to fill parameters/arguments requested by the OVF template wizard? ex: hostname/root password/ip address/gateway/etc...?  (I tryed via customization and its not working)..  I think its possible to do it with the ovftool

### New or Affected Resource(s)

* vcd_vapp_vm

* Issue #0000

**Comment by Didainius** [comment]
Hello @emmanuelpare,
You are most probably looking after [guest properties](https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vapp_vm#guest_properties).

This is a very common way for guest customization. We have one example which demonstrates _guest_properties_ yet (although not being your exact case) https://registry.terraform.io/providers/vmware/vcd/latest/docs/guides/vm_guest_customization

I am very confident this is what you are after so closing this now, but feel free to reopen if you think otherwise.

**Comment by dwildcash** [comment]
Thanks Danius for your quick reply

does guest properties are the equivalent of Vapp properties found in the vsphere provider?  Ex: https://github.com/hashicorp/terraform-provider-vsphere/issues/1074

**Comment by Didainius** [comment]
@dwildcash,
They should be. The name comes from VCD UI.
You can find these parameters in `vcd_vapp` (vApp) , `vcd_vapp_vm` (VM withing vApp) and `vcd_vm` (standalone VM)

![image](https://user-images.githubusercontent.com/15804230/154684174-52e1e63f-a8c2-44dd-b0ee-7a51dc897ae1.png)

**Comment by dwildcash** [comment]
Thanks it all worked fine!
