### ISSUE TITLE
Import of Tier-0 Gateways into VCD

### ISSUE THREAD

**Issue by bogi0704** [vmware/terraform-provider-vcd#896]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We are using Terraform to Provision NSX-T Manager Ressources and VCD Ressources. We would like to import a finished T0-Gateway at the end of NSX-T provisioning. That would allow us to stay in the Terraform stack. Currently we have a break in the NSX-T TF -> VCD TF chain, in which we have to import the T0-Gateway manually. A Terraform ressource would also allow us to manage the tenant's external IP adresses via code.

This is what I am talking about:

![grafik](https://user-images.githubusercontent.com/39438845/183065334-adc26a3b-8b0e-4105-a32f-21bb3c889a0e.png)

### New or Affected Resource(s)

* vcd_nsxt_tier0_gateway

**Comment by Didainius** [comment]
@bogi0704 ,
I am sorry this took me so much to get to really read the issue properly, but I think what you're after is https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/external_network_v2#example-usage-nsx-t-tier-0-router-backed-external-network

The name is misleading because VCD has been changing UI names with every version (and soon it will be renamed again I think), but the API behind the scenes is "external network".

Could you check that this is actually what you're looking for?
