### ISSUE TITLE
vcd_nsxt_distributed_firewall_rule resource 

### ISSUE THREAD

**Issue by storbel** [vmware/terraform-provider-vcd#970]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Actually, the DFW ( Distributed Firewall )  resource **vcd_nsxt_distributed_firewall** consider the Firewall as whole, all the rule are managed  within one ressource by listing all the rules...once we update the first rule on the Firewall, all the rules will change ID's and are recreated, when checking the API, it seems that a rule can be managed a part, the request is to add a new resource that manage specific rule by name 

example: 

```hcl
resource "vcd_nsxt_distributed_firewall_rule " "my-rule-1" {
  org          = "my-org"
  vdc          = "my-vdc"
  edge_gateway = "my-edge-gateway"

  source {
    ip_sets = [vcd_ipset.test-ipset_src.name]
  }

  destination {
    dynamic_groups= [vcd_dynamic_group.test-dg1.name]
   ip_sets = [vcd_ipset.test-ipset_dest.name]
  }

  service = ["ap_profile1","ap_profile2",]
}
```

Link to the API : 
https://developer.vmware.com/apis/vmware-cloud-director/latest/cloudapi/1.0.0/vdcGroups/vdcGroupId/dfwPolicies/policyId/rules/ruleId/put/

**Comment by Piedro1** [comment]
This one would really be appreciated, because logfiles (dfw-logs from log insight) don't contain vcd object names and depend on the ID NSX-T assigns to the fw-rule. It's very hard to correlate fw-rules with log rules, if the ID's change with every update of de fw-rule set.

**Comment by storbel** [comment]
@Didainius Hi, Any clue on when this enhancement can be taken in consideration ? do you think is technically possible ?

**Comment by Didainius** [comment]
@Piedro1, @storbel,
We are aiming to improve it in `v3.10.0`. I have yet to investigate the API more, but if there is API - we should be able to utilize it.

**Comment by Didainius** [comment]
Hello @storbel, @Piedro1 ,  
I am experimenting with a standalone firewall rule management resource `vcd_nsxt_distributed_firewall_rule` in draft pull request #1076 and would like to **ask for feedback.**

The structure itself would be very similar to existing `vcd_nsxt_distributed_firewall`, except for less nesting. 
By default, the resource would add a **rule to the bottom**, but there is also an option `above_rule_id` which can put the **rule above some other rule**.

Additionally, `vcd_vdc_group` is patched to have an additional option `remove_default_firewall_rule` which should help clear out default firewall rule (which could mess up working with firewall rules one by one as it would stay at the top)

One could build working code from #1076 as well as check docs there.

**Note** This would never work in parallel (provider will do internal locking and create rules one by one for each VDC Group) because there is no API for creating rules one by one. All the shuffling would is done in our SDK code.


```hcl
resource "vcd_nsxt_distributed_firewall_rule" "r1" {
  org          = "datacloud"
  vdc_group_id = vcd_vdc_group.test1.id

  name        = "rule1"
  action      = "ALLOW"
  description = "description"

  source_ids           = [vcd_nsxt_ip_set.set1.id, vcd_nsxt_ip_set.set2.id]
  destination_ids      = [vcd_nsxt_security_group.g1-empty.id, vcd_nsxt_security_group.g2.id]
  app_port_profile_ids = [vcd_nsxt_app_port_profile.p1.id, data.vcd_nsxt_app_port_profile.WINS.id, data.vcd_nsxt_app_port_profile.FTP.id]
}

resource "vcd_nsxt_distributed_firewall_rule" "r2" {
  org          = "datacloud"
  vdc_group_id = vcd_vdc_group.test1.id

  above_rule_id = vcd_nsxt_distributed_firewall_rule.r1.id # Order management element
  name        = "rule2"
  action      = "DROP"
  ip_protocol = "IPV4"
}

resource "vcd_nsxt_distributed_firewall_rule" "r3" {
  org          = "datacloud"
  vdc_group_id = vcd_vdc_group.test1.id

  above_rule_id = vcd_nsxt_distributed_firewall_rule.r2.id # Order management element

  name      = "rule3"
  action    = "DROP"
  enabled   = false
  logging   = true
  direction = "IN_OUT"

  source_ids                  = [vcd_nsxt_ip_set.set1.id, vcd_nsxt_ip_set.set2.id]
  network_context_profile_ids = [
    data.vcd_nsxt_network_context_profile.cp1.id,
    data.vcd_nsxt_network_context_profile.cp2.id,
    data.vcd_nsxt_network_context_profile.cp3.id
  ]
}
```

**Comment by lvirbalas** [comment]
@storbel , @Piedro1 if you have a chance to provide feedback, please do - we are getting close to release. After we do that and the feature is out in the wilderness, we can't change it much anymore... Thank you in advance.
